require 'spec_helper'
require 'dealer_claims_controller.rb'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DealerClaimsController do

  # This should return the minimal set of attributes required to create a valid
  # DealerClaim. As you add validations to DealerClaim, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DealerClaimsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all dealer_claims as @dealer_claims" do
      dealer_claim = DealerClaim.new valid_attributes
      get :index, {}, valid_session
      assigns(:dealer_claims).should eq([dealer_claim])
    end
  end

  describe "GET show" do
    it "assigns the requested dealer_claim as @dealer_claim" do
      dealer_claim = DealerClaim.create! valid_attributes
      get :show, {:id => dealer_claim.to_param}, valid_session
      assigns(:dealer_claim).should eq(dealer_claim)
    end
  end

  describe "GET new" do
    it "assigns a new dealer_claim as @dealer_claim" do
      get :new, {}, valid_session
      assigns(:dealer_claim).should be_a_new(DealerClaim)
    end
  end

  describe "GET edit" do
    it "assigns the requested dealer_claim as @dealer_claim" do
      dealer_claim = DealerClaim.create! valid_attributes
      get :edit, {:id => dealer_claim.to_param}, valid_session
      assigns(:dealer_claim).should eq(dealer_claim)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DealerClaim" do
        expect {
          post :create, {:dealer_claim => valid_attributes}, valid_session
        }.to change(DealerClaim, :count).by(1)
      end

      it "assigns a newly created dealer_claim as @dealer_claim" do
        post :create, {:dealer_claim => valid_attributes}, valid_session
        assigns(:dealer_claim).should be_a(DealerClaim)
        assigns(:dealer_claim).should be_persisted
      end

      it "redirects to the created dealer_claim" do
        post :create, {:dealer_claim => valid_attributes}, valid_session
        response.should redirect_to(DealerClaim.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved dealer_claim as @dealer_claim" do
        # Trigger the behavior that occurs when invalid params are submitted
        DealerClaim.any_instance.stub(:save).and_return(false)
        post :create, {:dealer_claim => {}}, valid_session
        assigns(:dealer_claim).should be_a_new(DealerClaim)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DealerClaim.any_instance.stub(:save).and_return(false)
        post :create, {:dealer_claim => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested dealer_claim" do
        dealer_claim = DealerClaim.create! valid_attributes
        # Assuming there are no other dealer_claims in the database, this
        # specifies that the DealerClaim created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DealerClaim.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => dealer_claim.to_param, :dealer_claim => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested dealer_claim as @dealer_claim" do
        dealer_claim = DealerClaim.create! valid_attributes
        put :update, {:id => dealer_claim.to_param, :dealer_claim => valid_attributes}, valid_session
        assigns(:dealer_claim).should eq(dealer_claim)
      end

      it "redirects to the dealer_claim" do
        dealer_claim = DealerClaim.create! valid_attributes
        put :update, {:id => dealer_claim.to_param, :dealer_claim => valid_attributes}, valid_session
        response.should redirect_to(dealer_claim)
      end
    end

    describe "with invalid params" do
      it "assigns the dealer_claim as @dealer_claim" do
        dealer_claim = DealerClaim.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DealerClaim.any_instance.stub(:save).and_return(false)
        put :update, {:id => dealer_claim.to_param, :dealer_claim => {}}, valid_session
        assigns(:dealer_claim).should eq(dealer_claim)
      end

      it "re-renders the 'edit' template" do
        dealer_claim = DealerClaim.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DealerClaim.any_instance.stub(:save).and_return(false)
        put :update, {:id => dealer_claim.to_param, :dealer_claim => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested dealer_claim" do
      dealer_claim = DealerClaim.create! valid_attributes
      expect {
        delete :destroy, {:id => dealer_claim.to_param}, valid_session
      }.to change(DealerClaim, :count).by(-1)
    end

    it "redirects to the dealer_claims list" do
      dealer_claim = DealerClaim.create! valid_attributes
      delete :destroy, {:id => dealer_claim.to_param}, valid_session
      response.should redirect_to(dealer_claims_url)
    end
  end

end
